using System;
using System.Collections.Generic;
using System.Text;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by '.NET Wrapper Class Generator'
//     Product Version:1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WrapperGenerator.UI
{
	internal partial class WrappingOptions
	{
		public event System.EventHandler MethodsListViewSelectedIndexChanged;

		public event System.EventHandler PropertiesListViewSelectedIndexChanged;

		public event System.EventHandler EventsListViewSelectedIndexChanged;

		// ***************************************************************
		// This method should be called by the user-provided constructor!
		//***************************************************************
		private void InitializeWrapper ()
		{
			this.methodsListView.SelectedIndexChanged += this.OnMethodsListViewSelectedIndexChanged;
			this.propertiesListView.SelectedIndexChanged += this.OnPropertiesListViewSelectedIndexChanged;
			this.eventsListView.SelectedIndexChanged += this.OnEventsListViewSelectedIndexChanged;
		}

		private void OnMethodsListViewSelectedIndexChanged (Object sender, EventArgs e)
		{
			if ((this.MethodsListViewSelectedIndexChanged != null))
			{
				this.MethodsListViewSelectedIndexChanged (sender, e);
			}
		}

		private void OnPropertiesListViewSelectedIndexChanged (Object sender, EventArgs e)
		{
			if ((this.PropertiesListViewSelectedIndexChanged != null))
			{
				this.PropertiesListViewSelectedIndexChanged (sender, e);
			}
		}

		private void OnEventsListViewSelectedIndexChanged (Object sender, EventArgs e)
		{
			if ((this.EventsListViewSelectedIndexChanged != null))
			{
				this.EventsListViewSelectedIndexChanged (sender, e);
			}
		}
	}
}


